### PR TITLE
Fix: bug cause by biocframe in col_data of exps

### LINKED ISSUE #13: MAE does not support experiments with BiocFrame col_data
https://github.com/BiocPy/MultiAssayExperiment/blob/6a1d7d1854078cd37063f5c95140953f61d35d7e/src/multiassayexperiment/MultiAssayExperiment.py#L179

MAE also does not support BiocFrame col_data (you'll have to fix all the type hinting as well):

https://github.com/BiocPy/MultiAssayExperiment/blob/6a1d7d1854078cd37063f5c95140953f61d35d7e/src/multiassayexperiment/MultiAssayExperiment.py#L135

Prolly other issues related to BiocFrame, not bother ing to find them all.

### PR DESCRIPTION
**Pull request by DiDeoxy**
Fixes #13

### CODE REVIEW

**Comment by DiDeoxy** [comment]
@jkanche in case is still doesn't autoping you

**Comment by jkanche** [comment]
you may also want to strictly version the `biocframe` package dependency in setup.py. the newer version 0.5.2 is probably gonna break things everywhere

**Comment by DiDeoxy** [comment]
I changed it to draft as there could be more changes needed (testing)

**Comment by jkanche** [comment]
this package should probably use an older version of biocframe, either 0.3.20 or 0.4.1.

**Comment by jkanche** [comment]
I believe with #17 merged, this is not necessary anymore.

**Pull request closed without merging**
